require("vagag")
require("vagag.remap")
require("vagag.set")
require("vagag.packer")
require("vagag.telescope")
require("vagag.colorscheme")
require("vagag.treesitter")
require("vagag.lsp")
require("vagag.cmp")

